# Import theme
remote_theme: totaldebug/jekyll-theme-cv

title: Steven Marks - Resume
url: https://resume.totaldebug.uk
description: The Resume for Steven Marks

plugins:
- jekyll-remote-theme

analytics: G-82YDYT2TG2
